application: petit-imgpost3
version: 1
runtime: python310
api_version: 1
threadsafe: yes

app_engine_apis: true

env_variables:
  BUCKET_NAME: "my-image-bucket"

libraries:
# - name: webapp2
#   version: latest

# - name: jinja2
#   version: latest
  
# - name: PIL
#   version: latest
# libraries:
  - name: grpcio
    version: 1.0.0
  - name: setuptools
    version: 36.6.0

handlers:
- url: /static
  static_dir: static

# - url: /static/(.*)
#   static_files: static/\1
#   upload: static/(.*)

- url: /css
  mime_type: text/css
  static_dir: css

- url: /(\w*)/css/(.*\.css)$
  mime_type: text/css
  static_files: \1/static/css/\2
  upload: (\w*)/static/css/(.*\.css)$

- url: /js
  mime_type: text/javascript
  static_dir: js

- url: /images
  static_dir: images

- url: /(\w*)/images/(.*\.(gif|png|jpg|jpeg))
  static_files: \1/static/images/\2
  upload: (\w*)/static/images/(.*\.(gif|png|jpg|jpeg))

- url: /.*
  script: routes.application

entrypoint: gunicorn -b :$PORT main:app
